name: weather-app-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Install project dependencies
        run: |
          composer install --prefer-dist
      - name: Run linter and tests
        run: |
          make check